### ISSUE TITLE
Public Assets OpenAPI section doesn't expand the endpoints

### ISSUE THREAD

**Issue by honourfish** [jitsuin-inc/rkvst-docs#359]
## Description

Public Assets OpenAPI section doesn't expand the endpoints

### Steps to reproduce

goto: https://docs.rkvst.com/docs/api-reference/public-assets-api/#public-assets-openapi-docs

Click on any api endpoint, it doesn't expand

### Expected result

Each endpoint should expand

### Actual result

No endpoints expand

### Environment

docs.rkvst.com

**Comment by CamrynCarter** [comment]
Resolved by fixing title conventions in swagger.
